# Generated by Django 3.0.3 on 2020-02-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_text', models.CharField(max_length=250)),
                ('hazard_part', models.CharField(choices=[('1', 'PART I'), ('2', 'PART II'), ('3', 'PART III'), ('4', 'PART IV')], default='1', max_length=1)),
            ],
        ),
    ]
